language: python
install:
    - pip install esptool
    - pip install ampy
    - pip install https://www.github.com/esp-32-micropython-installer/v0_1.tar.gz
script:
    - python -m esp32micropy --test
    
